class RandomPlayerActions: 
    def __init__(self, id, seed): ...

    def _draw_or_trade(self): ...

    def _trade(self): ...
    
    def _provide_bidding(self, state): ...
    
    def _buy_or_sell(self, state): ...

    def _send_money_to_player(self, player, amount): ...
    
    def _respond_to_trade(self, offer): ...
    
    def _receive_game_update(self, update): ...
